openapi: 3.0.3

info:
  title: '%API_TITLE%'
  version: '%API_VERSION%'

paths: { }

components:
  examples:
    UserCollectionResponse:
      value:
        data:
          - type: users
            id: 00000000-0000-0000-0000-000000000000
            attributes:
              firstName: Jane
              lastName: Smith
              email: jane.smith@example.com
              emailVerifiedAt: 2022-02-02T20:22:02.000000Z
              role: user
              createdAt: 2022-02-02T20:22:02.000000Z
              updatedAt: 2022-02-02T20:22:02.000000Z
            links:
              self: https://example.com/users/00000000-0000-0000-0000-000000000000

    UserResponse:
      value:
        data:
          type: users
          id: 00000000-0000-0000-0000-000000000000
          attributes:
            firstName: Jane
            lastName: Smith
            email: jane.smith@example.com
            emailVerifiedAt: 2022-02-02T20:22:02.000000Z
            role: user
            createdAt: 2022-02-02T20:22:02.000000Z
            updatedAt: 2022-02-02T20:22:02.000000Z
          links:
            self: https://example.com/users/00000000-0000-0000-0000-000000000000

    UserCreateRequest:
      value:
        data:
          type: users
          attributes:
            firstName: Jane
            lastName: Smith
            email: jane.smith@example.com
            role: user

    UserUpdateRequest:
      value:
        data:
          type: users
          id: 00000000-0000-0000-0000-000000000000
          attributes:
            firstName: Jane
            lastName: Smith
            email: jane.smith@example.com
            role: user
